# actions.yaml
# This workflow will install Python dependencies, trains, tests, builds, containerizes the code
name: Python app
on:
  push:
    branches: 
      - main
      - test
  pull_request:
    branches: 
      - main
      - test
jobs:
docker:
runs-on: ubuntu-latest
steps:
- name: Checkout repository
uses: actions/checkout@v3
- name: install requirements
run: pip install -r requirements/requirements.txt
- name: Install Test requirements
run: pip install -r requirements/test_requirements.txt
- name: Install build package
run: pip install build
- name: Run training pipeline
run: python bikeshare_model/train_pipeline.py
- name : Execute unit testcases
run: pytest
- name: Build Model to generage whl file
run: python -m build
- name: Log in to DockerHub
run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_UNAME }}" --password-stdin
- name: Build and push Docker image
run: |
docker build -t ${{ secrets.DOCKERHUB_UNAME }}/bike_sharing_api:latest .
docker push ${{ secrets.DOCKERHUB_UNAME }}/bike_sharing_api:latest
Rename main.yml to main_test.yml · AIMLOPS-B/bikeshare_project@550c85c · GitHub
  
